/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TextPresenter.java
 *
 * Created on 20 Αυγ 2010, 5:01:12 μμ
 */

package KAnalyzer.Utils;

import KAnalyzer.Utils.ReportTools.ReportFormat;

/**
 *
 * @author Ioannis Charalampidis <johnys2@gmail.com>
 */
public class TextPresenter extends KAnalyzer.API.TPresenter {

    /** Creates new form TextPresenter */
    public TextPresenter() {
        initComponents();
    }

    public void writeLine(String s) {
        write(s + "\n");
    }

    public void write(String s ) {
        jTextData.setText(jTextData.getText()+s);
    }

    public void clear() {
        jTextData.setText("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextData = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();

        jTextData.setFont(jTextData.getFont().deriveFont(jTextData.getFont().getSize()+1f));
        jScrollPane1.setViewportView(jTextData);

        jButton1.setText("Save to file");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jToggleButton1.setText("Include to report");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 397, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jToggleButton1)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReportTools.saveReportDialog(this);
}//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextPane jTextData;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    @Override
    public String getReport(ReportFormat format) {
        if (format == ReportFormat.CSV) {
            return " ==[ " + Title + " ]==========================\n\n" + jTextData.getText();
        } else if (format == ReportFormat.HTML) {
            return "<h2>" + Title + "</h2>\n<pre>" + jTextData.getText() + "</pre>";
        }
        return Title + "\n" + jTextData.getText();
    }

    @Override
    public void reset() {
        jTextData.setText("");
    }

    @Override
    public boolean includeToReport() {
        return jToggleButton1.isSelected();
    }

}
