/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Presenter.java
 *
 * Created on 26 Ιουλ 2010, 11:33:23 μμ
 */

package KAnalyzer.API;
import KAnalyzer.Utils.ReportTools.ReportFormat;
        
/**
 *
 * @author Ioannis Charalampidis <johnys2@gmail.com>
 */
public abstract class TPresenter extends javax.swing.JPanel implements IReportable {

    /** API Properties **/
    public String Title;
    public TAnalyzeTarget target;

    /** API Functions **/
    public abstract void reset();

    /** Reportable Implementation **/
    @Override
    public abstract String getReport( ReportFormat format );
    @Override
    public abstract boolean includeToReport();
    @Override
    public String getTitle() {
        return Title;
    }

    /** Creates new form Presenter */
    public TPresenter() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 516, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 267, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

}
